spring:
  application:
    name: Unichess-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/unichess
    username: unichess
    password: unichess
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  logging:
    level:
      liquibase: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: DEBUG