spring:
  application:
    name: Unichess-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/unichess_stg
    username: unichess_stg
    password: unichess_stg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-stg.xml
  logging:
    level:
      liquibase: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
